import type { Source, SourceType, SourceStatus } from '@/types/source';

export const mockSources: Source[] = [
  {
    id: 'src-001',
    title: 'Responsible AI Practices: A Comprehensive Guide',
    type: 'pdf',
    authors: ['Dr. Sarah Chen', 'Prof. Michael Torres'],
    publicationDate: '2025-03-15',
    publisher: 'AI Ethics Press',
    url: null,
    doi: '10.1234/rai-2025-001',
    language: 'en',
    description:
      'A comprehensive guide covering best practices for building responsible AI systems, including fairness, transparency, and accountability frameworks.',
    tags: ['AI Ethics', 'Fairness', 'Transparency'],
    contentSensitivity: 'low',
    internalNotes: 'Updated version with new Chapter 7 on bias mitigation.',
    status: 'indexed',
    errorMessage: null,
    indexedAt: '2025-06-01T10:30:00Z',
    createdAt: '2025-05-28T14:00:00Z',
    updatedAt: '2025-06-01T10:30:00Z',
    filePath: '/uploads/responsible-ai-guide.pdf',
    thumbnailUrl: null,
  },
  {
    id: 'src-002',
    title: 'RAG Systems and Knowledge Retrieval',
    type: 'pdf',
    authors: ['Dr. James Whitfield'],
    publicationDate: '2025-01-20',
    publisher: 'Tech Research Journal',
    url: 'https://example.com/rag-systems-paper',
    doi: null,
    language: 'en',
    description: 'An in-depth analysis of Retrieval-Augmented Generation architectures and their applications in enterprise knowledge management.',
    tags: ['RAG', 'Knowledge Management', 'Enterprise AI'],
    contentSensitivity: 'medium',
    internalNotes: 'Contains proprietary benchmark data — restrict access to senior researchers.',
    status: 'indexed',
    errorMessage: null,
    indexedAt: '2025-05-30T08:15:00Z',
    createdAt: '2025-05-29T09:00:00Z',
    updatedAt: '2025-05-30T08:15:00Z',
    filePath: '/uploads/rag-systems.pdf',
    thumbnailUrl: null,
  },
  {
    id: 'src-003',
    title: 'Privacy-First AI: Design Principles',
    type: 'webpage',
    authors: ['Elena Rodriguez', 'Anika Patel'],
    publicationDate: '2025-04-10',
    publisher: 'Digital Rights Foundation',
    url: 'https://example.com/privacy-first-ai',
    doi: null,
    language: 'en',
    description: 'Exploring design principles for building AI systems that prioritize user privacy and data protection from the ground up.',
    tags: ['Privacy', 'Data Protection', 'Design'],
    contentSensitivity: 'low',
    internalNotes: null,
    status: 'processing',
    errorMessage: null,
    indexedAt: null,
    createdAt: '2025-06-03T11:20:00Z',
    updatedAt: '2025-06-03T11:20:00Z',
    filePath: null,
    thumbnailUrl: null,
  },
  {
    id: 'src-004',
    title: 'AI Governance Framework — Internal Policy v3',
    type: 'text',
    authors: ['Compliance Team'],
    publicationDate: '2025-05-01',
    publisher: null,
    url: null,
    doi: null,
    language: 'en',
    description: 'Internal governance policy document outlining the organizational AI ethics review process and compliance requirements.',
    tags: ['Governance', 'Policy', 'Compliance'],
    contentSensitivity: 'high',
    internalNotes: 'Board-approved version. Do not share externally.',
    status: 'indexed',
    errorMessage: null,
    indexedAt: '2025-06-02T16:45:00Z',
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-06-02T16:45:00Z',
    filePath: '/uploads/ai-governance-v3.md',
    thumbnailUrl: null,
  },
  {
    id: 'src-005',
    title: 'Deep Learning for NLP — Lecture Series',
    type: 'youtube',
    authors: ['Stanford CS224N'],
    publicationDate: '2025-02-14',
    publisher: 'YouTube',
    url: 'https://www.youtube.com/watch?v=rmVRLeJRQn4',
    doi: null,
    language: 'en',
    description: 'Stanford CS224N lecture series covering deep learning techniques for natural language processing.',
    tags: ['NLP', 'Deep Learning', 'Education'],
    contentSensitivity: 'low',
    internalNotes: null,
    status: 'queued',
    errorMessage: null,
    indexedAt: null,
    createdAt: '2025-06-04T09:00:00Z',
    updatedAt: '2025-06-04T09:00:00Z',
    filePath: null,
    thumbnailUrl: 'https://img.youtube.com/vi/rmVRLeJRQn4/hqdefault.jpg',
  },
  {
    id: 'src-006',
    title: 'Interview: The Future of Conversational AI',
    type: 'audio',
    authors: ['Tech Talks Podcast', 'Dr. Lisa Wang'],
    publicationDate: '2025-05-22',
    publisher: 'Tech Talks Network',
    url: null,
    doi: null,
    language: 'en',
    description: 'A podcast interview with Dr. Lisa Wang discussing the future direction of conversational AI and ethical considerations.',
    tags: ['Conversational AI', 'Podcast', 'Ethics'],
    contentSensitivity: 'low',
    internalNotes: 'Transcription completed. Needs review for accuracy.',
    status: 'error',
    errorMessage: 'Audio transcription failed: unsupported codec. Please re-upload in MP3 or WAV format.',
    indexedAt: null,
    createdAt: '2025-06-02T15:30:00Z',
    updatedAt: '2025-06-03T07:00:00Z',
    filePath: '/uploads/interview-conversational-ai.m4a',
    thumbnailUrl: null,
  },
  {
    id: 'src-007',
    title: 'Bias Detection in Language Models',
    type: 'pdf',
    authors: ['Dr. Amara Osei', 'Prof. Yuki Tanaka', 'Dr. Rahul Sharma'],
    publicationDate: '2025-04-28',
    publisher: 'Journal of AI Research',
    url: 'https://example.com/bias-detection-lm',
    doi: '10.1234/jair-2025-042',
    language: 'en',
    description: 'Novel methodologies for detecting and measuring bias in large language models with case studies from GPT and BERT families.',
    tags: ['Bias Detection', 'Language Models', 'Fairness'],
    contentSensitivity: 'medium',
    internalNotes: null,
    status: 'processing',
    errorMessage: null,
    indexedAt: null,
    createdAt: '2025-06-04T13:45:00Z',
    updatedAt: '2025-06-04T13:45:00Z',
    filePath: '/uploads/bias-detection-lm.pdf',
    thumbnailUrl: null,
  },
  {
    id: 'src-008',
    title: 'Understanding Transformer Architectures',
    type: 'youtube',
    authors: ['3Blue1Brown'],
    publicationDate: '2025-03-08',
    publisher: 'YouTube',
    url: 'https://www.youtube.com/watch?v=zd89r4e4OM4',
    doi: null,
    language: 'en',
    description: 'Visual explanation of transformer architectures, self-attention mechanisms, and how they power modern AI.',
    tags: ['Transformers', 'Education', 'Visualization'],
    contentSensitivity: 'low',
    internalNotes: null,
    status: 'indexed',
    errorMessage: null,
    indexedAt: '2025-05-25T12:00:00Z',
    createdAt: '2025-05-24T18:00:00Z',
    updatedAt: '2025-05-25T12:00:00Z',
    filePath: null,
    thumbnailUrl: 'https://img.youtube.com/vi/zd89r4e4OM4/hqdefault.jpg',
  },
];

export const mockProcessingLogs: Record<string, { timestamp: string; message: string }[]> = {
  'src-001': [
    { timestamp: '2025-05-28T14:00:00Z', message: 'File uploaded successfully' },
    { timestamp: '2025-05-28T14:00:30Z', message: 'Queued for processing' },
    { timestamp: '2025-05-28T14:01:00Z', message: 'Extracting text from PDF (42 pages)' },
    { timestamp: '2025-05-28T14:03:00Z', message: 'Text extraction complete' },
    { timestamp: '2025-05-28T14:03:30Z', message: 'Generating embeddings' },
    { timestamp: '2025-06-01T10:30:00Z', message: 'Indexing complete — 42 pages, 387 chunks indexed' },
  ],
  'src-002': [
    { timestamp: '2025-05-29T09:00:00Z', message: 'File uploaded successfully' },
    { timestamp: '2025-05-29T09:00:30Z', message: 'Queued for processing' },
    { timestamp: '2025-05-29T09:01:00Z', message: 'Extracting text from PDF (28 pages)' },
    { timestamp: '2025-05-30T08:15:00Z', message: 'Indexing complete — 28 pages, 245 chunks indexed' },
  ],
  'src-003': [
    { timestamp: '2025-06-03T11:20:00Z', message: 'URL submitted for crawling' },
    { timestamp: '2025-06-03T11:20:30Z', message: 'Crawling webpage content...' },
    { timestamp: '2025-06-03T11:21:00Z', message: 'Generating embeddings...' },
  ],
  'src-004': [
    { timestamp: '2025-06-01T10:00:00Z', message: 'File uploaded successfully' },
    { timestamp: '2025-06-01T10:00:30Z', message: 'Queued for processing' },
    { timestamp: '2025-06-01T10:01:00Z', message: 'Parsing markdown content' },
    { timestamp: '2025-06-02T16:45:00Z', message: 'Indexing complete — 156 chunks indexed' },
  ],
  'src-005': [
    { timestamp: '2025-06-04T09:00:00Z', message: 'YouTube URL submitted' },
    { timestamp: '2025-06-04T09:00:30Z', message: 'Queued for processing' },
  ],
  'src-006': [
    { timestamp: '2025-06-02T15:30:00Z', message: 'File uploaded successfully' },
    { timestamp: '2025-06-02T15:31:00Z', message: 'Starting audio transcription' },
    { timestamp: '2025-06-03T07:00:00Z', message: 'Error: Audio transcription failed — unsupported codec' },
  ],
  'src-007': [
    { timestamp: '2025-06-04T13:45:00Z', message: 'File uploaded successfully' },
    { timestamp: '2025-06-04T13:45:30Z', message: 'Extracting text from PDF (67 pages)' },
    { timestamp: '2025-06-04T13:48:00Z', message: 'Generating embeddings...' },
  ],
  'src-008': [
    { timestamp: '2025-05-24T18:00:00Z', message: 'YouTube URL submitted' },
    { timestamp: '2025-05-24T18:01:00Z', message: 'Fetching transcript' },
    { timestamp: '2025-05-24T18:02:00Z', message: 'Generating embeddings' },
    { timestamp: '2025-05-25T12:00:00Z', message: 'Indexing complete — 342 chunks indexed' },
  ],
};

export function getSourceById(id: string): Source | undefined {
  return mockSources.find((s) => s.id === id);
}

export function getSourcesByType(type: SourceType): Source[] {
  return mockSources.filter((s) => s.type === type);
}

export function getSourcesByStatus(status: SourceStatus): Source[] {
  return mockSources.filter((s) => s.status === status);
}
