import type { Source, SourceType } from '@/types/source';

export const mockSources: Source[] = [
  {
    id: 'src-001',
    title: 'Responsible AI Practices: A Comprehensive Guide',
    type: 'pdf',
    authors: ['Dr. Sarah Chen', 'Prof. Michael Torres'],
    publicationDate: '2025-03-15',
    publisher: 'AI Ethics Press',
    url: '',
    doi: '10.1234/rai-2025-001',
    language: 'en',
    description:
      'A comprehensive guide covering best practices for building responsible AI systems, including fairness, transparency, and accountability frameworks.',
    tags: ['AI Ethics', 'Fairness', 'Transparency'],
    contentSensitivity: 'low',
    internalNotes: 'Updated version with new Chapter 7 on bias mitigation.',
    status: 'indexed',
    errorMessage: null,
    chunkCount: 387,
  },
  {
    id: 'src-002',
    title: 'RAG Systems and Knowledge Retrieval',
    type: 'pdf',
    authors: ['Dr. James Whitfield'],
    publicationDate: '2025-01-20',
    publisher: 'Tech Research Journal',
    url: 'https://example.com/rag-systems-paper',
    doi: null,
    language: 'en',
    description: 'An in-depth analysis of Retrieval-Augmented Generation architectures and their applications in enterprise knowledge management.',
    tags: ['RAG', 'Knowledge Management', 'Enterprise AI'],
    contentSensitivity: 'medium',
    internalNotes: 'Contains proprietary benchmark data — restrict access to senior researchers.',
    status: 'indexed',
    errorMessage: null,
    chunkCount: 245,
  },
  {
    id: 'src-003',
    title: 'Privacy-First AI: Design Principles',
    type: 'webpage',
    authors: ['Elena Rodriguez', 'Anika Patel'],
    publicationDate: '2025-04-10',
    publisher: 'Digital Rights Foundation',
    url: 'https://example.com/privacy-first-ai',
    doi: null,
    language: 'en',
    description: 'Exploring design principles for building AI systems that prioritize user privacy and data protection from the ground up.',
    tags: ['Privacy', 'Data Protection', 'Design'],
    contentSensitivity: 'low',
    internalNotes: null,
    status: 'indexed',
    errorMessage: null,
    chunkCount: 15,
  },
  {
    id: 'src-004',
    title: 'AI Governance Framework — Internal Policy v3',
    type: 'text',
    authors: ['Compliance Team'],
    publicationDate: '2025-05-01',
    publisher: null,
    url: '',
    doi: null,
    language: 'en',
    description: 'Internal governance policy document outlining the organizational AI ethics review process and compliance requirements.',
    tags: ['Governance', 'Policy', 'Compliance'],
    contentSensitivity: 'high',
    internalNotes: 'Board-approved version. Do not share externally.',
    status: 'indexed',
    errorMessage: null,
    chunkCount: 156,
  },
  {
    id: 'src-005',
    title: 'Deep Learning for NLP — Lecture Series',
    type: 'youtube',
    authors: ['Stanford CS224N'],
    publicationDate: '2025-02-14',
    publisher: 'YouTube',
    url: 'https://www.youtube.com/watch?v=rmVRLeJRQn4',
    doi: null,
    language: 'en',
    description: 'Stanford CS224N lecture series covering deep learning techniques for natural language processing.',
    tags: ['NLP', 'Deep Learning', 'Education'],
    contentSensitivity: 'low',
    internalNotes: null,
    status: 'processing',
    errorMessage: null,
    chunkCount: 48,
  },
  {
    id: 'src-006',
    title: 'Interview: The Future of Conversational AI',
    type: 'audio',
    authors: ['Tech Talks Podcast', 'Dr. Lisa Wang'],
    publicationDate: '2025-05-22',
    publisher: 'Tech Talks Network',
    url: '',
    doi: null,
    language: 'en',
    description: 'A podcast interview with Dr. Lisa Wang discussing the future direction of conversational AI and ethical considerations.',
    tags: ['Conversational AI', 'Podcast', 'Ethics'],
    contentSensitivity: 'low',
    internalNotes: 'Transcription completed. Needs review for accuracy.',
    status: 'error',
    errorMessage: 'Audio transcription failed: unsupported codec.',
    chunkCount: 32,
  },
  {
    id: 'src-007',
    title: 'Bias Detection in Language Models',
    type: 'pdf',
    authors: ['Dr. Amara Osei', 'Prof. Yuki Tanaka', 'Dr. Rahul Sharma'],
    publicationDate: '2025-04-28',
    publisher: 'Journal of AI Research',
    url: 'https://example.com/bias-detection-lm',
    doi: '10.1234/jair-2025-042',
    language: 'en',
    description: 'Novel methodologies for detecting and measuring bias in large language models with case studies from GPT and BERT families.',
    tags: ['Bias Detection', 'Language Models', 'Fairness'],
    contentSensitivity: 'medium',
    internalNotes: null,
    status: 'processing',
    errorMessage: null,
    chunkCount: 210,
  },
  {
    id: 'src-008',
    title: 'Understanding Transformer Architectures',
    type: 'youtube',
    authors: ['3Blue1Brown'],
    publicationDate: '2025-03-08',
    publisher: 'YouTube',
    url: 'https://www.youtube.com/watch?v=zd89r4e4OM4',
    doi: null,
    language: 'en',
    description: 'Visual explanation of transformer architectures, self-attention mechanisms, and how they power modern AI.',
    tags: ['Transformers', 'Education', 'Visualization'],
    contentSensitivity: 'low',
    internalNotes: null,
    status: 'indexed',
    errorMessage: null,
    chunkCount: 342,
  },
];

export function getSourceById(id: string): Source | undefined {
  return mockSources.find((s) => s.id === id);
}

export function getSourcesByType(type: SourceType): Source[] {
  return mockSources.filter((s) => s.type === type);
}
